### ISSUE TITLE
Would this be suitable for a Scala editor?

### ISSUE THREAD

**Issue by Sciss** [pavelfatin/toyide#1]
Hi Pavel; thanks for this project. I know it's meant to be educational only, but I find the editor already very useful, and the source code is readable and not too large, so I'm contemplating whether I could build a Scala language support, perhaps delegating lexing and parsing to scalameta. What would be your assessment? Would this work out, or is the API too limited/different to support Scala as a language?

Would you consider changing the licenes to a more liberal library license, such as LGPL?

Thanks!

**Comment by pavelfatin** [comment]
Hi Hanns,

I guess, it very much depends on a particular use case:

For a general-purpose IDE, something like IntelliJ Platform is a sure winner, both in terms of the API capabilities and in terms of the already supported functionality (languages, frameworks, etc). If you need a platform that is time-tested and production-ready, I definitely recommend you to choose IntelliJ.

Yet, if you need something that is lightweight and highly tunable, for a very specific purpose, you may consider using the project code for that. In principle, it should be possible to implement Scala support on top of the existing architecture, even though it was initially created with the educational goal in mind.

Sure, I can update the license, if need be, to LGPL or to ALv2 (especially, considering that I've recently changed the license from GPLv3 to APv2 for https://github.com/pavelfatin/typometer).

(by the way, properly supporting Scala language is no easy feat, check for example https://github.com/jetbrains/intellij-scala)

**Comment by Sciss** [comment]
I was thinking about IntelliJ Platform or NetBeans Platform, but indeed I want something simpler for specific purpose and tunable, and it doesn't need to be fully fledged IDE. I know Scala support isn't easy, I'm still evaluating the easiest path with perhaps scalameta. For sure I don't intend to write my own lexer/parser.

**Comment by pavelfatin** [comment]
Implementing lexer / parser / AST is actually a pretty straightforward task, even if done by hand, besides, there are [JFlex](http://jflex.de/) and [ANTLR](http://www.antlr.org/), which can generate all that automatically from the [language grammar](https://www.scala-lang.org/files/archive/spec/2.11/13-syntax-summary.html) (for IntelliJ Platform there's [Grammar-Kit](https://plugins.jetbrains.com/plugin/6606-grammar-kit)). It's reference resolution and type inference where things start to get tricky.

You can probably start with any API, simply to get a feel for task, and then you can refine your requirements along the way (IntelliJ Platform has a [fairly good documentation](https://www.jetbrains.org/intellij/sdk/docs/welcome.html), including a [tutorial on how to add custom language support](https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html)).

**Comment by Sciss** [comment]
I see. Indeed, I just patched in the lexer from Scalariform, and it works great: https://github.com/Sciss/toyide/blob/sbtfied/scalalang/src/main/scala/de/sciss/scalalang/ScalaLexer.scala

I'll see in the next step about the parser, and then the third step is probably to implement an LSP client to get the type inference...

> Sure, I can update the license, if need be, to LGPL or to ALv2 (especially, considering that I've recently changed the license from GPLv3 to APv2 for https://github.com/pavelfatin/typometer).

That would be great; either of the two would work for me.

**Comment by pavelfatin** [comment]
I've relicensed the code under ALv2.

If you have any questions, feel free to write me an email (mail@pavelfatin.com).

**Comment by Sciss** [comment]
Thank you!
